
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import minggu_12.Kelas;
import minggu_12.Mahasiswa;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Bagus_Anggriawan
 */
public class NewJFrame extends javax.swing.JFrame {

    private DefaultListModel listModel;
    private DefaultListModel listModel2;
    Kelas kelasA;
    Kelas kelasB;
    int index = -1;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {

        Mahasiswa m1 = new Mahasiswa("A01", "Bagus", 100);
        

        kelasA = new Kelas("2 D3 IT A", "Bu Renovita");
        kelasA.addMhs(m1);
        
//       

        Mahasiswa r1 = new Mahasiswa("B01", "Sahputra", 90);
  

        kelasB = new Kelas("2 D3 IT B", "Bu Indah");
        kelasB.addMhs(r1);
        

        initComponents();
        listModel = new DefaultListModel();
        listModel2 = new DefaultListModel();
        listModel.addAll(kelasA.getListMhs());
        listModel2.addAll(kelasB.getListMhs());
        KelasA.setModel(listModel);
        jList2.setModel(listModel2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        Tambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        KelasA = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        Clear = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtnilaiuas = new javax.swing.JTextField();
        txtnilaitugas = new javax.swing.JTextField();
        txtnilaiuts = new javax.swing.JTextField();
        Hitung = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        outRerata = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        outRerata2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        outRerata3 = new javax.swing.JLabel();
        hitung_akhir = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        outakhir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tambah.setText("Add");
        Tambah.setName("BOK"); // NOI18N
        Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahActionPerformed(evt);
            }
        });
        getContentPane().add(Tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 283, -1, -1));

        KelasA.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        KelasA.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                KelasAValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(KelasA);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 28, 191, 100));

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 28, 192, 100));

        jLabel1.setText("Kelas A");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 6, 50, -1));

        jLabel2.setText("Kelas B");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 6, -1, -1));

        jLabel3.setText("NRP");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 149, 64, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 146, 90, -1));

        jLabel4.setText("Nama");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 178, 64, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 175, 90, -1));

        jLabel5.setText("Nilai Akhir");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 208, 64, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 206, 90, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kelas A", "Kelas B" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 237, 90, -1));

        jLabel6.setText("Kelas");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 238, 64, -1));

        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        getContentPane().add(Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 283, -1, -1));

        jLabel7.setText("Nilai Tugas");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, -1, -1));

        jLabel8.setText("Nilai UTS");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, -1, -1));

        jLabel9.setText("Nilai UAS");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, -1, -1));
        getContentPane().add(txtnilaiuas, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 90, -1));

        txtnilaitugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnilaitugasActionPerformed(evt);
            }
        });
        getContentPane().add(txtnilaitugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 90, -1));

        txtnilaiuts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnilaiutsActionPerformed(evt);
            }
        });
        getContentPane().add(txtnilaiuts, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 90, -1));

        Hitung.setText("Hitung");
        Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungActionPerformed(evt);
            }
        });
        getContentPane().add(Hitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, -1, -1));

        jLabel10.setText("Nilai Java");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 74, -1));
        getContentPane().add(outRerata, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 60, 16));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Java", "Konjar", "Web Progamming" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 125, -1));

        jLabel11.setText("Nilai Konjar");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 74, -1));
        getContentPane().add(outRerata2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 60, 16));

        jLabel12.setText("Nilai Web");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 74, -1));
        getContentPane().add(outRerata3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 60, 18));

        hitung_akhir.setText("Hitung Nilai Akhir");
        hitung_akhir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitung_akhirActionPerformed(evt);
            }
        });
        getContentPane().add(hitung_akhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 283, -1, -1));

        jLabel13.setText("Nilai Akhir");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 74, 22));
        getContentPane().add(outakhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 60, 22));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahActionPerformed
        String NRP = jTextField1.getText();
        String Nama = jTextField2.getText();
        double nilai_akhir = Double.valueOf(jTextField3.getText());
       

        Mahasiswa mhs = new Mahasiswa(NRP, Nama, nilai_akhir);

        if (jComboBox1.getSelectedIndex() == 0) {
            kelasA.addMhs(mhs);
            listModel.clear();
            listModel.addAll(kelasA.getListMhs());
//            List < Kelas > = KelasA.stream()
//            .sorted((o1, o2) -> (double)(o1.getNilai_akhir() - o2.getNilai_akhir())).collect(Collectors.toList());
        } else {
            kelasB.addMhs(mhs);
            listModel2.clear();
            listModel2.addAll(kelasB.getListMhs());
        }

    }//GEN-LAST:event_TambahActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
    }//GEN-LAST:event_ClearActionPerformed

    private void KelasAValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_KelasAValueChanged
//        
//if (index != -1){
//            jList1.setSelectedIndex(index);
//        } 

        if (KelasA.getValueIsAdjusting() == false) {
            System.out.println(KelasA.getValueIsAdjusting());

//            if (index != -1)
            KelasA.setSelectedIndex(index);
            index = KelasA.getSelectedIndex();

            System.out.println("List: " + index);

            Mahasiswa m = kelasA.getListMhs(index);
            jTextField1.setText(m.getNRP());
            jTextField2.setText(m.getNama());
            jTextField3.setText(String.valueOf(m.nilai_akhir));

        }

//        jButton1.setEnabled(false);
    }//GEN-LAST:event_KelasAValueChanged

    private void txtnilaiutsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnilaiutsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnilaiutsActionPerformed

    private void txtnilaitugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnilaitugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnilaitugasActionPerformed

    private void HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungActionPerformed
        if (jComboBox2.getSelectedIndex() == 0) {
            if (txtnilaitugas.getText().isEmpty() || txtnilaiuts.getText().isEmpty() || txtnilaiuas.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Inputan belum lengkap.");
            } else {
                Double rerata = (Double.parseDouble(txtnilaitugas.getText())
                        + Double.parseDouble(txtnilaiuts.getText()) + Double.parseDouble(txtnilaiuas.getText())) / 3;
                outRerata.setText(rerata.toString().substring(0, 5));
            }
        } else if (jComboBox2.getSelectedIndex() == 1) {
            if (txtnilaitugas.getText().isEmpty() || txtnilaiuts.getText().isEmpty() || txtnilaiuas.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Inputan belum lengkap.");
            } else {
                Double rerata = (Double.parseDouble(txtnilaitugas.getText())
                        + Double.parseDouble(txtnilaiuts.getText()) + Double.parseDouble(txtnilaiuas.getText())) / 3;
                outRerata2.setText(rerata.toString().substring(0, 5));
            }
        } else {
            if (txtnilaitugas.getText().isEmpty() || txtnilaiuts.getText().isEmpty() || txtnilaiuas.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Inputan belum lengkap.");
            } else {
                Double rerata = (Double.parseDouble(txtnilaitugas.getText())
                        + Double.parseDouble(txtnilaiuts.getText()) + Double.parseDouble(txtnilaiuas.getText())) / 3;
                outRerata3.setText(rerata.toString().substring(0, 5));
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_HitungActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void hitung_akhirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitung_akhirActionPerformed
         Double rerata = (Double.parseDouble(outRerata.getText())
                        + Double.parseDouble(outRerata2.getText()) + Double.parseDouble(outRerata3.getText())) / 3;
                outakhir.setText(rerata.toString().substring(0, 5));
    }//GEN-LAST:event_hitung_akhirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JButton Hitung;
    private javax.swing.JList<String> KelasA;
    private javax.swing.JButton Tambah;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton hitung_akhir;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel outRerata;
    private javax.swing.JLabel outRerata2;
    private javax.swing.JLabel outRerata3;
    private javax.swing.JLabel outakhir;
    private javax.swing.JTextField txtnilaitugas;
    private javax.swing.JTextField txtnilaiuas;
    private javax.swing.JTextField txtnilaiuts;
    // End of variables declaration//GEN-END:variables
}
